version: "4.6"

services:
  redis:
    image: redis:7-alpine
    container_name: new-signagewala-redis
    restart: always
    command: >
      redis-server 
      --appendonly yes
      --requirepass admin123
    ports:
      - "6380:6379" # safe port
    volumes:
      - redis-data:/data

volumes:
  redis-data:

# redis://:admin123@localhost:6380
